export { default as Loader } from "./Loader/Loader";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Review } from "./Review/Review";
export { default as Special } from "./Special/Special";
export { default as Star } from "./Star/Star";
export { default as BookingForm } from "./Booking/BookingForm/BookingForm";
export { default as FinalPage } from "./Booking/FinalPage/FinalPage";
export { default as PaymentForm } from "./Booking/PaymentForm/PaymentForm";
export { default as ReviewPage } from "./Booking/ReviewPage/ReviewPage";
